### ISSUE TITLE
Graduate conda-lock to main conda organization

### ISSUE THREAD

**Issue by mariusvniekerk** [conda/conda-lock#319]
As conda-lock has been stably in use by much of the greater conda ecosystem and has been reliable for quite some time, *I would like to graduate conda-lock to the main conda organization*.

We have a small but sufficiently active core group of constributors between myself @maresb and @bollwyvl with some occasional assistance from @wolfv .  Graduation would mean that we can more easily establish the conda-lock format as a standard specification that can be used by conda/mamba to install environments with.

**Comment by mariusvniekerk** [comment]
@conda-incubator/steering

This proposal falls under the [Incorporate a Software Project into the main conda Organization](https://github.com/conda-incubator/governance/tree/eaf59a5779dc1f678bee4453ceb92fd733e7306a#incorporate-a-software-project-into-the-main-conda-organization) policy of the [conda governance policy](https://github.com/conda-incubator/governance), please vote and/or comment on this proposal.

It needs 60% of the Steering Council to vote yes to pass.

To vote, please leave yes, no or abstain as comments below this issue.

If you have questions concerning the proposal, please leave a comment below as well.

*This vote will end on 2023-01-28.*

**Comment by msarahan** [comment]
yes - good addition, Marius. Thanks others for helping to maintain.

**Comment by beckermr** [comment]
Yes.

**Comment by jakirkham** [comment]
Yes

**Comment by jezdez** [comment]
Yes

**Comment by xhochy** [comment]
Yes

**Comment by jaimergp** [comment]
Yes!

**Comment by ocefpaf** [comment]
Yes!

**Comment by chenghlee** [comment]
Yes

**Comment by marcelotrevisani** [comment]
Yes!

**Comment by goanpeca** [comment]
yes

**Comment by mbargull** [comment]
Yes

**Comment by jezdez** [comment]
## Voting Results

This was a standard, non-timed-out vote.

Among [Steering Council members](https://github.com/conda-incubator/governance/blob/963a16ee02126229ec57614b000e3480d8cea26d/steering.csv) there are 11 "yes", 0 "no", and no abstentions.

This vote **has reached quorum** (11 is at least 60% of 15).

It **has also passed** since it recorded 11 "yes" votes and 0 "no" votes giving 11/11 which is greater than 60% of 11.

**Comment by jezdez** [comment]
The repo has been transferred to the conda organization and the conda-lock team from the incubator recreated: https://github.com/conda/conda-lock

@ericdill @maresb @ocefpaf @mariusvniekerk @scopatz Please check your emails for invitations to the conda organization. Also please let me know if you plan to NOT join the team in the conda org. Thank you!

**Comment by jezdez** [comment]
The majority of maintainers have joined the project team. There are probably changes needed to update URLs etc.

**Comment by jezdez** [comment]
Other than #324, I've also opened https://github.com/conda/infra/pull/676 to automatically sync the Conda Code of Conduct to the conda-lock repo.

@conda/conda-lock If you would like to use any of the OTHER GitHub config files from the infra repo, please let me know. We have standard files for:

- issue and pull request templates
- standardized issue labels
- rever files etc

Here's the full sync config: https://github.com/conda/infra/blob/main/.github/sync/config.yml

Since conda-lock has probably an own set of practices, I want to clarify that these things are optional, even the Code of Conduct sync as we have one centrally configured in https://github.com/conda/.github/blob/main/CODE_OF_CONDUCT.md. It may be useful for some people to have the file available in the repo directly, though.

If you have suggestions for the change, feedback is very welcome.

**Comment by dbast** [comment]
Seems the repo had renovate activated before the move, there is still the [Dependency Dashboard](https://github.com/conda/conda-lock/issues/215) and config file https://github.com/conda/conda-lock/blob/main/renovate.json ... Should renovate be activated again?

**Comment by jezdez** [comment]
@dbast Good catch, I've enabled it again for conda-lock.

**Comment by jezdez** [comment]
Closing since I think all of the steps needed for the graduation have been done.

@conda/conda-lock Please file issues in the https://github.com/conda/infrastructure repo in case you need help with any of the GitHub org setup.
