### ISSUE TITLE
Default platforms are unexpectedly added from multiple sources

### ISSUE THREAD

**Issue by maresb** [conda/conda-lock#337]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

If I use both `pyproject.toml` and a supplemental `environment.yml` as sources, and if I specify platforms in `pyproject.toml` but not in `environment.yml`, I would expect the resulting platforms to be the list from `pyproject.toml`. Instead it's those platforms union the default platforms (linux-64, osx-64, win-64).

The logic in [`parse_source_files`](https://github.com/conda/conda-lock/blob/d04563cd8f2001e64316eb46975781bcda29d9ce/conda_lock/conda_lock.py#L869) looks odd to me. It seems like we add the default platforms if they are missing from _any_ source file (except for `pyproject.toml`?).

I would have expected that we take the union of all platforms from all source files, and then substitute the default platforms only if that were empty.

Ping @srilman since this involves code we've been looking at recently.

**Comment by srilman** [comment]
I agree, this is really odd behavior. I think this is because for Conda source files like `meta.yaml` and `environment.yml` files, we need to know the list of platforms before we actually start parsing the file in order for OS preprocessor selectors to work correctly. However, as I think you suggested in https://github.com/conda/conda-lock/issues/278#issuecomment-1371407231, what we should really do is parse the source files once to get the platforms, and then parse them again to get the list of dependencies.

**Comment by srilman** [comment]
Since we were planning to split #316 into smaller pieces anyways, I think I can do the following to get this problem fixed first:
- Take out the first 2 commits and move to a separate PR. You mentioned that you already reviewed them, so it should be easy to get the new PR merged.
- Open a PR to fix this specific behavior, without using a new `SourceFile` class
- Then rebase and split #316 further to make reviewing easier.
